- gschema:
    id: org.gnome.shell
    filename: zz0-00-extensions.gschema.override
    settings:
      enabled-extensions:
        - accent-directories@taiwbi.com
        - appindicatorsupport@rgcjonas.gmail.com
        - blur-my-shell@aunetx
        - caffeine@patapon.info
        - disable-workspace-switcher-overlay@cleardevice
        - gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com
        - hotedge@jonathan.jdoda.ca
        - ideapad@laurento.frittella
        - just-perfection-desktop@just-perfection
        - splashindicator@ochi12.github.com
        - wireless-hid@chlumskyvaclav.gmail.com
        - window-centering@hnjjhmtr27
        - zena-shell@jianzcar.github

- gschema:
    id: org.gnome.desktop.interface
    filename: zz0-01-desktop.gschema.override
    settings:
      accent-color: 'slate'
      color-scheme: 'prefer-light'
      gtk-theme: 'adw-gtk3'
      clock-format: '12h'
      clock-show-seconds: true
      enable-hot-corners: false
      monospace-font-name: 'JetBrains Mono 11'

- gschema:
    id: org.gnome.desktop.sound
    filename: zz0-02-sound.gschema.override
    settings:
      allow-volume-above-100-percent: true

- gschema:
    id: org.gnome.mutter
    filename: zz0-03-mutter.gschema.override
    settings:
      center-new-windows: false

- gschema:
    id: org.gnome.desktop.peripherals.mouse
    filename: zz0-04-mouse.gschema.override
    settings:
      accel-profile: 'flat'

- gschema:
    id: org.gnome.desktop.peripherals.touchpad
    filename: zz0-05-touchpad.gschema.override
    settings:
      click-method: 'default'
      tap-and-drag-lock: true
      two-finger-scrolling-enabled: false
      edge-scrolling-enabled: true

- gschema:
    id: org.gnome.Ptyxis
    filename: zz0-06-ptyxis.gschema.override
    settings:
      interface-style: 'system'
      restore-session: false

- path: /etc/dconf/db/local.d/00-blurmyshell-panel
  content: |
    [org/gnome/shell/extensions/blur-my-shell/panel]
    blur=false

- path: /etc/dconf/db/local.d/01-blurmyshell-overview
  content: |
    [org/gnome/shell/extensions/blur-my-shell/overview]
    style-components=3

- path: /etc/dconf/db/local.d/02-just-perfection
  content: |
    [org/gnome/shell/extensions/just-perfection]
    workspace-wrap-around=true

- path: /etc/dconf/db/local.d/03-appfolders
  content: |
    [org/gnome/desktop/app-folders]
    folder-children=['AudioVideo', 'Development', 'Education', 'Games', 'Graphics', 'Network', 'Office', 'Science', 'Settings', 'System', 'Utilities', 'Wine']

    [org/gnome/desktop/app-folders/folders/AudioVideo]
    name='Audio & Video'
    categories=['AudioVideo']

    [org/gnome/desktop/app-folders/folders/Development]
    name='Development'
    categories=['Development']

    [org/gnome/desktop/app-folders/folders/Education]
    name='Education'
    categories=['Education']

    [org/gnome/desktop/app-folders/folders/Games]
    name='Games'
    categories=['Game']

    [org/gnome/desktop/app-folders/folders/Graphics]
    name='Graphics'
    categories=['Graphics']

    [org/gnome/desktop/app-folders/folders/Network]
    name='Internet'
    categories=['Network']

    [org/gnome/desktop/app-folders/folders/Office]
    name='Office'
    categories=['Office']

    [org/gnome/desktop/app-folders/folders/Science]
    name='Science'
    categories=['Science']

    [org/gnome/desktop/app-folders/folders/Settings]
    name='Settings'
    categories=['Settings']

    [org/gnome/desktop/app-folders/folders/System]
    name='System'
    categories=['System']

    [org/gnome/desktop/app-folders/folders/Utilities]
    name='Utilities'
    categories=['Utility']

    [org/gnome/desktop/app-folders/folders/Wine]
    name='Wine'
    categories=['X-Wine']

- path: /etc/dconf/profile/user
  content: |
    user-db:user
    system-db:local

# Allow writing conservation_mode without sudo password
- path: /etc/sudoers.d/ideapad
  content: |
    %wheel ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC2004\:00/conservation_mode

- path: /etc/modules
  content: |
    ideapad_laptop

# To allow old controllers to connect
- path: /etc/modprobe.d/disable-ertm.conf
  content: |
    options bluetooth disable_ertm=Y

- path: /usr/lib/sysusers.d/sysusers-custom.conf
  content: |
    u avahi - "Avahi mDNS daemon" /var/run/avahi-daemon
    g avahi - "Avahi mDNS daemon"

    u abrt - "ABRT user" /etc/abrt
    g abrt - "ABRT group"

    u wsdd - "WSDD service user" /var/lib/wsdd
